title: Ethan Witwer
description: ""

url: "https://www.ethanwitwer.com"
email: ethan@ethanwitwer.com

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
#twitter: "#"
linkedin: "ethanwitwer"
#stackoverflow: "#"
github: "ewitwer"
#researchgate: "#"
orcid: "0009-0006-8038-5693"
#quora: "#"
#instagram: "#"
#facebook: "#"


# Markdown
highlighter: rouge
markdown: kramdown

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
#collections:
#  projects:
#    output: true
#    permalink: /projects/:name/
#    order:
#      - shortProject.md
#      - longerProjectTitle.md
#      - redirect.md
#      - project4.md
#      - project5.md
#      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
